sudo: false
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
cache:
  yarn: true
  directories:
    - 'node_modules'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
services:
  - mongodb
before_script:
  - yarn run lerna run prepublish
script:
  - yarn test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
deploy:
  provider: script
  script: 'yarn run publish'
  skip_cleanup: true
  on:
    node: '12'
    tags: true
